name: Self-Assign Bot

on:
  issue_comment:
    types: [created]

jobs:
  self-assign:
    runs-on: ubuntu-latest

    steps:
      - name: Check if comment is on PR
        if: github.event.issue.pull_request != null
        run: |
          # Extract the PR number from the comment payload
          pr_number=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          # Get the comment body
          comment_body=$(jq --raw-output .comment.body "$GITHUB_EVENT_PATH")
          # Extract the username mentioned in the comment body
          mentioned_user=$(echo "$comment_body" | grep -o '@[[:alnum:]]*' | head -1 | sed 's/@//')

          # Check if a username was mentioned
          if [ -n "$mentioned_user" ]; then
            # Assign the PR to the mentioned user using GitHub API
            curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/AnonymousCodes911/stingray/issues/$pr_number/assignees" \
              -d "{\"assignees\": [\"$mentioned_user\"]}"
          fi
